from tkinter import *

screen = Tk()
screen.geometry("800x300")
screen.title("Basics")
screen.configure(background="black")

Label(screen, text="Grilled Cheese", font=45).pack()
foody = Frame(screen, background = "cyan", width=300, height=400, border = 2)
foody.pack(side=LEFT)
pc = Frame(screen, background = "yellow", width=300, height=300, border = 2)
pc.pack(side=RIGHT)
bread = Frame(screen, background = "red", width=300, height=100, border = 2)
bread.pack(side=TOP)

sb = Scrollbar(pc)
sb.pack(side=RIGHT, fill=Y)

listbox = Listbox(pc, height=100, width=40, bg="blue", activestyle="underline")
listbox.insert(1, "Great")
listbox.insert(2, "Great")
listbox.insert(3, "Great")
listbox.insert(4, "Great")
listbox.insert(5, "Great")
listbox.insert(6, "Great")
listbox.insert(7, "Great")
listbox.insert(8, "Great")
listbox.insert(1, "Great")
listbox.insert(2, "Great")
listbox.insert(3, "Great")
listbox.insert(4, "Great")
listbox.insert(5, "Great")
listbox.insert(6, "Great")
listbox.insert(7, "Great")
listbox.insert(8, "Great")
listbox.insert(1, "Great")
listbox.insert(2, "Great")
listbox.insert(3, "Great")
listbox.insert(4, "Great")
listbox.insert(5, "Great")
listbox.insert(6, "Great")
listbox.insert(7, "Great")
listbox.insert(8, "Great")
for i in range(30):
    listbox.insert(END, i)    
listbox.pack()

sb.config(command=listbox.yview)

b1 = Button(foody, text="Grilled Cheese Sandwich L")
b1.pack(side=LEFT)
b2 = Button(foody, text="Grilled Cheese Sandwich B")
b2.pack(side=BOTTOM)
b3 = Button(foody, text="Grilled Cheese Sandwich B")
b3.pack(side=BOTTOM)
b1 = Button(foody, text="Grilled Cheese Sandwich R")
b1.pack(side=RIGHT)
b2 = Button(foody, text="Grilled Cheese Sandwich T")
b2.pack(side=TOP)
b3 = Button(foody, text="Grilled Cheese Sandwich T")
b3.pack(side=TOP)

screen.mainloop()